removeTrailingWhitespace: 1
indentRules:
  tabular: "\t"
lookForAlignDelims:
  table: 1
  tabular:
    delimiterRegEx: (?<!\\)(&)(?![^{}]*\})
  tabularx: 1
  longtable: 1
  array: 1
  matrix: 1

verbatimEnvironments:
  texlst: 1
